### ISSUE TITLE
color issues

### ISSUE THREAD

**Issue by Soneji** [Salomon-MH/BetterWhatsappWeb#1]
When trying your code with the latest wa web there are color issues

**Comment by Salomon-MH** [comment]
> When trying your code with the latest wa web there are color issues

@overclockedllama Sorry for the really delayed answer, but I recently pushed some fixes. Does it work for you now?

**Comment by Salomon-MH** [comment]
Closed as no answer was provided. If you have any issues, feel free to reopen this issue or create a new one. 😊

**Comment by Soneji** [comment]
Sorry, I must have missed this. Thanks, it is working much better now :D
